name: airplane
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  another_flushbar: ^1.12.29


  flutter_local_notifications: ^13.0.0
  shared_preferences: ^2.0.18
  flutter_bloc: ^8.1.2
  fluttertoast: ^8.2.1
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  google_sign_in: ^6.0.0
  intl: ^0.17.0
  image_picker: ^0.8.7
  flutter_svg: ^2.0.4
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  firebase_messaging: ^14.3.0
  firebase_storage: ^11.0.16
  firebase_auth: ^4.3.0
  day_night_switcher: ^0.2.0+1
  connectivity_plus: ^3.0.3
  shimmer: ^2.0.0
  dio: ^5.1.0
  dropdown_button2: ^2.0.0
  msh_checkbox: ^2.0.1
  sqflite: ^2.2.6
  lottie: ^2.3.1
  toggle_switch: ^2.0.1
  google_maps_flutter: ^2.2.8
  geocoding: ^2.1.0
  syncfusion_flutter_maps: ^21.1.38
  http: ^0.13.5
  georouter: ^0.0.1+1
  flutter_polyline_points: ^1.0.0
  line_animator: ^1.0.0+3
  geolocator: ^9.0.2
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  permission_handler: ^10.2.0
  chips_choice: ^3.0.0
  awesome_dialog: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_plugin_android_lifecycle: ^2.0.16



dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21



  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/user.png
    - assets/icons/
    - assets/fonts/



  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200

    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200

    - family: IconBroken
      fonts:
        - asset: assets/fonts/icon/icons.ttf



